name: Docker-Build

on: 
  push: 
    branches: [ main ]
    paths-ignore: [.github/**]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: docker login
        uses: docker/login-action@v2
        with: 
          registry: ${{ secrets.CONTAINER_REG }}.azurecr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Run Dockle
        uses: erzz/dockle-action@v1
        with:
          image: ${{ secrets.DOCKER_USER }}.azurecr.io/review-api:${{ github.sha }}
          exit-code: 0

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}.azurecr.io/review-api:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKER_USER }}.azurecr.io/review-api:${{ github.sha }}"
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        
      - name: Push Image to ACR
        run: |
          docker push  ${{ secrets.DOCKER_USER }}.azurecr.io/review-api:${{ github.sha }} 
      
